name: Getting Started
label: ["simple", "getting-started"]
body:
  - type: textarea
    attributes:
      label: Output of `brew config`
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output of `brew doctor`
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of issue
    validations:
      required: true
