title: Tap maintenance and Homebrew development
labels: ["advanced", "tap-maintenance-and-brew-development"]
body:
  - type: textarea
    attributes:
      label: Output of `brew config`
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output of `brew doctor`
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of issue
    validations:
      required: true
